# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt-Homework/homework-2/gui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BinaryTree(object):
    def setupUi(self, BinaryTree):
        BinaryTree.setObjectName("BinaryTree")
        BinaryTree.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(BinaryTree)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        BinaryTree.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BinaryTree)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        BinaryTree.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BinaryTree)
        self.statusbar.setObjectName("statusbar")
        BinaryTree.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(BinaryTree)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(BinaryTree)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(BinaryTree)
        QtCore.QMetaObject.connectSlotsByName(BinaryTree)

    def retranslateUi(self, BinaryTree):
        _translate = QtCore.QCoreApplication.translate
        BinaryTree.setWindowTitle(_translate("BinaryTree", "BinaryTree"))
        self.menuFile.setTitle(_translate("BinaryTree", "File"))
        self.actionOpen.setText(_translate("BinaryTree", "Open"))
        self.actionOpen.setShortcut(_translate("BinaryTree", "Ctrl+O"))
        self.actionQuit.setText(_translate("BinaryTree", "Quit"))
        self.actionQuit.setShortcut(_translate("BinaryTree", "Ctrl+Q"))
