# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CsvEditor(object):
    def setupUi(self, CsvEditor):
        CsvEditor.setObjectName("CsvEditor")
        CsvEditor.resize(825, 715)
        CsvEditor.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.centralwidget = QtWidgets.QWidget(CsvEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        CsvEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CsvEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 825, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        CsvEditor.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(CsvEditor)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(CsvEditor)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(CsvEditor)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionEnglish = QtWidgets.QAction(CsvEditor)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionRussian = QtWidgets.QAction(CsvEditor)
        self.actionRussian.setObjectName("actionRussian")
        self.actionAbout = QtWidgets.QAction(CsvEditor)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(CsvEditor)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(CsvEditor)
        QtCore.QMetaObject.connectSlotsByName(CsvEditor)

    def retranslateUi(self, CsvEditor):
        _translate = QtCore.QCoreApplication.translate
        CsvEditor.setWindowTitle(_translate("CsvEditor", "CsvEditor"))
        self.menuFile.setTitle(_translate("CsvEditor", "File"))
        self.menuHelp.setTitle(_translate("CsvEditor", "Help"))
        self.actionOpen.setText(_translate("CsvEditor", "Open"))
        self.actionOpen.setShortcut(_translate("CsvEditor", "Ctrl+O"))
        self.actionSave.setText(_translate("CsvEditor", "Save"))
        self.actionSave.setShortcut(_translate("CsvEditor", "Ctrl+S"))
        self.actionSave_as.setText(_translate("CsvEditor", "Save as"))
        self.actionSave_as.setShortcut(_translate("CsvEditor", "Ctrl+Shift+S"))
        self.actionEnglish.setText(_translate("CsvEditor", "English"))
        self.actionRussian.setText(_translate("CsvEditor", "Russian"))
        self.actionAbout.setText(_translate("CsvEditor", "About"))
        self.actionQuit.setText(_translate("CsvEditor", "Quit"))
        self.actionQuit.setShortcut(_translate("CsvEditor", "Ctrl+Q"))
